Repository brpoplpush/brpoplpush-redis_script, pull requests merged in 2019-10, with the labels that each got.

#1 Extract LUA script code from sidekiq-unique-jobs
  .editorconfig
  .gitignore
  .reek.yml
  .rspec
  .rubocop.yml
  .travis.yml
  Appraisals
  CHANGELOG.md
  CODE_OF_CONDUCT.md
  Gemfile
  Guardfile
  LICENSE.txt
  README.md
  Rakefile
  bin/console
  bin/setup
  brpoplpush-redis_script.gemspec
  gemfiles/.bundle/config
  gemfiles/redis_3.x.gemfile
  gemfiles/redis_3.x.gemfile.lock
  gemfiles/redis_4.x.gemfile
  gemfiles/redis_4.x.gemfile.lock
  lib/brpoplpush/redis_script.rb
  lib/brpoplpush/redis_script/client.rb
  lib/brpoplpush/redis_script/config.rb
  lib/brpoplpush/redis_script/error.rb
  lib/brpoplpush/redis_script/logging.rb
  lib/brpoplpush/redis_script/template.rb
  lib/brpoplpush/redis_script/timing.rb
  lib/brpoplpush/redis_script/version.rb
  lib/tasks/changelog.rake
  spec/brpoplpush/redis_script/client_spec.rb
  spec/brpoplpush/redis_script_spec.rb
  spec/spec_helper.rb
  spec/support/lua/shared/_common.lua
  spec/support/lua/shared/_current_time.lua
  spec/support/lua/test.lua
Labels: ready for review

#6 Delete License.txt
  LICENSE.txt
Labels: documentation

#7 Update docs and fix release scripts
  Guardfile
  brpoplpush-redis_script.gemspec
  gemfiles/redis_3.x.gemfile.lock
  gemfiles/redis_4.x.gemfile.lock
  update_docs.sh
Labels: bug, ready for review

#9 Prepare for using code climate (for fun and profit)
  .codeclimate.yml
  .travis.yml
  README.md
Labels: enhancement, ready for review

#10 Force the correct minium ruby version
  bin/console
  brpoplpush-redis_script.gemspec
Labels: ready for review

#11 Cleanup more leftovers from unique jobs
  .yardopts
  Rakefile
  lib/brpoplpush/redis_script/error.rb
Labels: bug, documentation, ready for review

#12 Feature/improve gem configuration
  .markdownlintrc
  .reek.yml
  .simplecov
  .travis.yml
  Gemfile
  README.md
  gemfiles/redis_3.x.gemfile
  gemfiles/redis_3.x.gemfile.lock
  gemfiles/redis_4.x.gemfile
  gemfiles/redis_4.x.gemfile.lock
  lib/brpoplpush/redis_script.rb
  lib/brpoplpush/redis_script/client.rb
  lib/brpoplpush/redis_script/config.rb
  lib/brpoplpush/redis_script/dsl.rb
  lib/brpoplpush/redis_script/logging.rb
  lib/brpoplpush/redis_script/lua_error.rb
  lib/brpoplpush/redis_script/script.rb
  lib/brpoplpush/redis_script/scripts.rb
  lib/brpoplpush/redis_script/template.rb
  lib/brpoplpush/redis_script/timing.rb
  spec/brpoplpush/redis_script/client/execute_spec.rb
  spec/brpoplpush/redis_script/client_spec.rb
  spec/brpoplpush/redis_script/config_spec.rb
  spec/brpoplpush/redis_script/lua_error_spec.rb
  spec/brpoplpush/redis_script/scripts_spec.rb
  spec/brpoplpush/redis_script_spec.rb
  spec/integration/sidekiq_unique_jobs/scripts.rb
  spec/integration/sidekiq_unique_jobs/scripts_spec.rb
  spec/spec_helper.rb
  spec/support/lua/lock.lua
  spec/support/lua/shared/_common.lua
  spec/support/lua/test.lua
  spec/support/redis.rb
  spec/support/shared_contexts.rb
Labels: ready for review

#16 Fix the build after 0.1.1 bump
  gemfiles/redis_3.x.gemfile.lock
  gemfiles/redis_4.x.gemfile.lock
Labels: bug, ready for review

#13 Make explicit what the name of the parameter is
  lib/tasks/changelog.rake
Labels: ready for review

#15 Minor README and gitignore update
  .gitignore
  README.md
Labels: documentation

#2 Create FUNDING.yml
  .github/FUNDING.yml
Labels: ready for review
